/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import javax.swing.JOptionPane;

/**
 *
 * @author igorg
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastrar = new javax.swing.JMenu();
        itemCadastrarProduto = new javax.swing.JMenuItem();
        itemProduto = new javax.swing.JMenuItem();
        itemCadastrarUsuario = new javax.swing.JMenuItem();
        mnuMovimentacao = new javax.swing.JMenu();
        itemFazerCompra = new javax.swing.JMenuItem();
        itemFazerPedido = new javax.swing.JMenuItem();
        itemMostrarPedidos = new javax.swing.JMenuItem();
        itemManutencaoPedido = new javax.swing.JMenuItem();
        itemManutencaoClientes = new javax.swing.JMenuItem();
        itemManutencaoProdutos = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        itemIntegrantes = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnuCadastrar.setText("Cadastrar");

        itemCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemCadastrarProduto.setText("Fornecedor");
        itemCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarProdutoActionPerformed(evt);
            }
        });
        mnuCadastrar.add(itemCadastrarProduto);

        itemProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemProduto.setText("Produto");
        itemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProdutoActionPerformed(evt);
            }
        });
        mnuCadastrar.add(itemProduto);

        itemCadastrarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemCadastrarUsuario.setText("Usuario");
        itemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarUsuarioActionPerformed(evt);
            }
        });
        mnuCadastrar.add(itemCadastrarUsuario);

        jMenuBar1.add(mnuCadastrar);

        mnuMovimentacao.setText("Movimentação");

        itemFazerCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemFazerCompra.setText("Realizar Compra");
        itemFazerCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFazerCompraActionPerformed(evt);
            }
        });
        mnuMovimentacao.add(itemFazerCompra);

        itemFazerPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemFazerPedido.setText("Realizar Pedido");
        itemFazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFazerPedidoActionPerformed(evt);
            }
        });
        mnuMovimentacao.add(itemFazerPedido);

        itemMostrarPedidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemMostrarPedidos.setText("Pedidos emitidos");
        itemMostrarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarPedidosActionPerformed(evt);
            }
        });
        mnuMovimentacao.add(itemMostrarPedidos);

        itemManutencaoPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemManutencaoPedido.setText("Manutenção pedido");
        itemManutencaoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManutencaoPedidoActionPerformed(evt);
            }
        });
        mnuMovimentacao.add(itemManutencaoPedido);

        itemManutencaoClientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemManutencaoClientes.setText("Manutenção clientes");
        itemManutencaoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManutencaoClientesActionPerformed(evt);
            }
        });
        mnuMovimentacao.add(itemManutencaoClientes);

        itemManutencaoProdutos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemManutencaoProdutos.setText("Manutenção produtos");
        itemManutencaoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemManutencaoProdutosActionPerformed(evt);
            }
        });
        mnuMovimentacao.add(itemManutencaoProdutos);

        jMenuBar1.add(mnuMovimentacao);

        mnuAjuda.setText("Ajuda");

        itemIntegrantes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemIntegrantes.setText("Sobre nós");
        itemIntegrantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIntegrantesActionPerformed(evt);
            }
        });
        mnuAjuda.add(itemIntegrantes);

        itemSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        mnuAjuda.add(itemSair);

        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemManutencaoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManutencaoPedidoActionPerformed
        ManutencaoPedido telaManutPed = new ManutencaoPedido();
        telaManutPed.setVisible(true);
    }//GEN-LAST:event_itemManutencaoPedidoActionPerformed

    private void itemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarUsuarioActionPerformed
        cadastroUsuario telacad = new cadastroUsuario();
        telacad.setVisible(true);
    }//GEN-LAST:event_itemCadastrarUsuarioActionPerformed

    private void itemMostrarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarPedidosActionPerformed

    }//GEN-LAST:event_itemMostrarPedidosActionPerformed

    private void itemCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarProdutoActionPerformed
        CadastrarFornecedor telaCadCli = new CadastrarFornecedor();
        telaCadCli.setVisible(true);
               
    }//GEN-LAST:event_itemCadastrarProdutoActionPerformed

    private void itemManutencaoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManutencaoClientesActionPerformed

    }//GEN-LAST:event_itemManutencaoClientesActionPerformed

    private void itemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdutoActionPerformed
        CadastrarProduto telaCadProd = new CadastrarProduto();
        telaCadProd.setVisible(true);
    }//GEN-LAST:event_itemProdutoActionPerformed

    private void itemManutencaoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemManutencaoProdutosActionPerformed
        ManutencaoProduto telaManutProd = new ManutencaoProduto();
        telaManutProd.setVisible(true);
    }//GEN-LAST:event_itemManutencaoProdutosActionPerformed

    private void itemIntegrantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIntegrantesActionPerformed
        JOptionPane.showMessageDialog(null, "Sistema desenvolvido por : \nIgor Gomes da Silva \nKauã Silva Dias \nGuilherme Cordeiro Rodrigues");
    }//GEN-LAST:event_itemIntegrantesActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemFazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFazerPedidoActionPerformed
        Pedido telaPedido = new Pedido();
        telaPedido.setVisible(true);
    }//GEN-LAST:event_itemFazerPedidoActionPerformed

    private void itemFazerCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFazerCompraActionPerformed
        Compra telaCompra = new Compra();
        telaCompra.setVisible(true);
    }//GEN-LAST:event_itemFazerCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCadastrarProduto;
    private javax.swing.JMenuItem itemCadastrarUsuario;
    private javax.swing.JMenuItem itemFazerCompra;
    private javax.swing.JMenuItem itemFazerPedido;
    private javax.swing.JMenuItem itemIntegrantes;
    private javax.swing.JMenuItem itemManutencaoClientes;
    private javax.swing.JMenuItem itemManutencaoPedido;
    private javax.swing.JMenuItem itemManutencaoProdutos;
    private javax.swing.JMenuItem itemMostrarPedidos;
    private javax.swing.JMenuItem itemProduto;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuCadastrar;
    private javax.swing.JMenu mnuMovimentacao;
    // End of variables declaration//GEN-END:variables
}
